// AUTO-GENERATED by scripts/sync-experience-from-resume.mjs
// Source of truth: src/content/resume.md (## Employment)

export type Experience = {
  role: string
  company: {
    name: string
    href?: string
  }
  location: string
  start: string
  end?: string
  highlights: string[]
  tags: string[]
}

export const EXPERIENCE: Experience[] = [
  {
    role: 'Software Engineer',
    company: { name: 'Soundraw Inc.', href: 'https://soundraw.io' },
    location: 'Tokyo, Japan (Hybrid)',
    start: 'Jan 2025',
    highlights: [
      'Built and shipped mobile APIs for AI music creation and delivery.',
      'Owned improvements to soundraw.io, including new genres and a smoother creation flow.',
      'Generated 20,000+ songs in one week to support a $150K+ enterprise deal.'
    ],
    tags: [
      'Cloudflare',
      'Domain modeling',
      'FFmpeg',
      'Linear',
      'Ruby on Rails',
      'Vue',
      'Heroku',
      'Postgres',
      'MongoDB',
      'AI Agents'
    ]
  },
  {
    role: 'Software Engineer',
    company: { name: 'Kadric Smart Solutions', href: 'https://www.ksmartsolutions.jp' },
    location: 'Tokyo, Japan (Hybrid)',
    start: 'May 2023',
    end: 'Nov 2025',
    highlights: [
      'Guided customers through a Working Backwards process to turn business goals into technical specifications.',
      'Shipped logistics and autonomous-forklift management tools with React, TypeScript, MUI, and deck.gl.',
      'Delivered gateway, kiosk, and Android owner/kiosk-mode prototypes across Java/Spring, Node.js, and Vue.',
      'Planned and delivered a gateway project on a 2-month schedule, including Japanese client communication and documentation.'
    ],
    tags: [
      'Consulting',
      'React',
      'TypeScript',
      'Node.js',
      'Vue',
      'Java',
      'Spring',
      'MUI',
      'deck.gl',
      'AWS',
      'Terraform',
      'Japanese',
      'Docker',
      'Atlassian'
    ]
  },
  {
    role: 'Data Reliability Engineer',
    company: { name: 'Moneytree', href: 'https://getmoneytree.com' },
    location: 'Tokyo, Japan (Remote)',
    start: 'Jan 2020',
    end: 'Apr 2023',
    highlights: [
      'Owned reliability of financial data aggregation pipelines pulling from 3,000+ banks for 5,000,000+ users.',
      'Optimized dozens of integrations, reducing monthly running costs by 30%+.',
      'Built hundreds of monitoring/alerting tools, SQL templates, and SOPs to speed up incident response.'
    ],
    tags: [
      'Web and API scraping',
      'API integration',
      'Node.js',
      'TypeScript',
      'AWS',
      'Ruby on Rails',
      'SQL',
      'Redash',
      'Sumo Logic',
      'Atlassian',
      'Slack'
    ]
  },
  {
    role: 'Software Engineer',
    company: { name: 'Verball', href: 'https://www.verball.co' },
    location: 'Sao Paulo, Brazil (Remote)',
    start: 'Aug 2019',
    end: 'Dec 2019',
    highlights: [
      'Built voice-driven applications and back-end services for conversational experiences.'
    ],
    tags: [
      'Node.js',
      'JavaScript',
      'Google Cloud Platform (GCP)',
      'MySQL',
      'Firebase',
      'Actions on Google',
      'Google Assistant'
    ]
  },
  {
    role: 'Data Visualization Analyst (Internship)',
    company: { name: 'Mitsubishi Fuso Truck & Bus Corp.', href: 'https://mitsubishi-fuso.com' },
    location: 'Kawasaki, Japan (On-site)',
    start: 'Apr 2019',
    end: 'Oct 2019',
    highlights: [
      'Designed and implemented time-intelligent dashboards used for after-sales truck parts price revisions.',
      'Structured and prepared datasets consumed by pricing dashboards.'
    ],
    tags: ['Microsoft Power BI', 'DAX', 'SQL', 'Python', 'Microsoft Office']
  },
  {
    role: 'Software Engineer',
    company: { name: 'MuchMore Digital', href: 'https://muchmore.digital' },
    location: 'Recife, Pernambuco & Sao Paulo, Brazil (On-site)',
    start: 'Jul 2016',
    end: 'Feb 2019',
    highlights: [
      'Delivered CMS and APIs for large battery and automotive clients.',
      'Developed chatbot infrastructure and conversational dialogs for customer-facing products.',
      'Built data lake pipelines and ETL jobs for FCA Latam, including BI/marketing data views in BigQuery.',
      'Integrated Salesforce and Google Analytics APIs and automated recurring data jobs.',
      'Contributed to the open-source Zendesk Java Client with new models and wrapper updates.'
    ],
    tags: [
      'SQL',
      'GCP',
      'BigQuery',
      'Node.js',
      'JavaScript',
      'PHP',
      'Python',
      'Linux',
      'Git',
      'Cron jobs',
      'Java',
      'MongoDB',
      'Play Framework',
      'AngularJS',
      'Google Maps API',
      'Heroku',
      'IBM Watson',
      'GTM',
      'Zendesk Java Client',
      'Twitter API'
    ]
  }
]
